---

- name: Add registry to manager node
  hosts: manager
  roles:
    - common
    - docker
    - registry

- name: Basic installation to all the nodes
  hosts:
    - swarm-nodes
  roles:
    - common
    - docker
    - nfsshare

- name: Init swarm
  hosts:
  - swarm-managers
  roles:
    - dockermanager

- name: Init swarm
  hosts:
  - swarm-nodes
  roles:
    - dockernodes

- name: Add basics thinks to the docker swarm
  hosts: manager
  roles:
    - build_vault_ui
    - build_vault
    - vault
    - build_dealmaker
    - build_salesmaker
    - build_dealmaker_dmgr
    - build_salesmaker_dmgr
    - build_trusted_api
    - build_portainer
    - build_caliveapicreator
    - build_elk
    - build_traefik
    - build_mysql
    - mysql
    - traefik
#    - traefik-test # Traefik Test Containers
    - portainer
    - elk
    - dealmaker
    - salesmaker
    - dealmaker-dmgr
    - salesmaker-dmgr
    - caliveapicreator
    - caliveapicreator_loadapis
#
- name: Add Jenkins installation
  hosts: CI
  roles:
    - jenkins_final
